<script lang="ts">
export default async function () {
	return [
		/* **************** */
		"components/xExcalidraw/xExcalidraw",
		/* *************** */
		"components/other/xCollapse/xCollapseItem",
		"components/other/xCollapse/xCollapse",
		"components/other/xAlert/xAlert",
		"components/other/xProgress/xProgress",
		"components/TableCell/TableCell",
		"components/TableCell/TableCellItem",
		/*  */
		"components/base/layout/xRow",
		"components/base/layout/xCol",
		/*  */
		"components/base/xBtn/xBtnWithConfirm",
		"components/base/xDevlog/xDevlog",
		"components/base/xBtn/xBtn",
		"components/base/xBtn/xBtnArray",
		"components/base/xBtn/xBtnGroup",
		"components/base/xBtn/xColActionAndMore",
		/*  */
		"components/data/xChart/xChart",
		"components/data/xMenuTree/xMenuTree",
		/*  */
		"components/navigation/xMenu/xMenu",
		"components/navigation/xMenu/xMenuItem",
		"components/navigation/xMenu/xMenuItemGroup",
		"components/navigation/xMenu/xSubMenu",
		"components/navigation/xTabs/mobile/xMobileTabBar",
		"components/navigation/xTabs/xTabs",
		"components/navigation/xTabs/xTabPane",
		"components/data/xTag/xTag",
		"components/data/xDesc/xDesc",
		"components/data/xDesc/xItemDesc",
		"components/data/xTableVir/xTableVir",
		"components/data/xVirtualList/xFixedSizeList",
		"components/data/xPagination/xPagination",
		"components/data/xBadge/xBadge",
		"components/data/xTree/xTree",
		"components/data/xTree/xTreeNode",
		"components/data/xTree/xNodeContent",
		"components/form/xAdvancedSearch/xAdvancedSearch",
		"components/form/xInput/xInput",
		"components/form/xInputNumber/xInputNumber",
		"components/form/xIpAddress/xIpAddress",
		"components/form/xAutocomplete/xAutocomplete",
		"components/form/xAutocomplete/xAutocompleteSuggestions",
		"components/form/xSelect/xSelect",
		/* ******************** */
		"components/form/xCascader/xCascader",
		"components/form/xCascader/xCascaderPanel/xCascaderPanel",
		/* ******************** */
		"components/form/xSwitch/xSwitch",
		"components/form/xSlider/xSlider",
		"components/form/xRadio/xRadio",
		"components/form/xRadio/xRadioButton",
		"components/form/xRadio/xRadioGroup",
		"components/form/xCheckbox/xCheckbox",
		"components/form/xCheckbox/xCheckboxButton",
		"components/form/xCheckbox/xCheckboxGroup",
		"components/other/xAvatar/xAvatar",
		"components/other/xCalendar/xCalendar",
		"components/other/xDivider/xDivider",
		"components/other/xCard/xCard",
		"components/other/xTimeline/xTimeline",
		"components/other/xTimeline/xTimelineItem",
		"components/other/xBlock/xBlock",
		"components/other/xAffix/xAffix",
		/*  */
		"components/form/xDatePicker/xDatePicker",
		"components/form/xDatePicker/xTimePicker",
		"components/form/xDatePicker/xTimeSelect",
		"components/form/xSelect/xSelect",
		"components/form/xSelect/xOption",
		"components/form/xSelect/xOptionGroup",
		"components/form/xSelect/xSelectDropdown",
		/*  */
		"components/navigation/xPageHeader/xPageHeader",
		"components/navigation/xBreadcrumb/xBreadcrumb",
		"components/navigation/xBreadcrumb/xBreadcrumbItem",
		"components/navigation/xSteps/xSteps",
		"components/navigation/xSteps/xStep",
		"components/navigation/xDropdown/xDropdown",
		"components/navigation/xDropdown/xDropdownItem",
		"components/navigation/xDropdown/xDropdownMenu",
		/*  */
		"components/other/xScrollbar/xScrollbar",
		/* ********layout******* */
		"components/layout/page/xPageTitle",
		"components/layout/page/xPageContent",
		"components/layout/page/xPageFooter",
		/* *********directive********** */
		"directive/xImg/xImg",
		"directive/xTooltip/xTooltip",
		"directive/xDrawer/xDrawer",
		"directive/xtips/xPopover",
		/* ********************** */
		"common/xAppLayoutHeaderOcOprs",
		"common/xMd",
		"common/xItemWrapper",
		"common/xAutoResizer",
		"common/xCellBtnGroup",
		"common/xCellDate",
		"common/xCellEllipsis",
		"common/xCellInput",
		"common/xCellCheckbox",
		"common/xCellOptions",
		"common/xCellRate",
		"common/xCellSelect",
		"common/xCellSelectSearch",
		"common/xCellSelectOrInput",
		"common/xCellText",
		"common/xColActions",
		"common/xDialog",
		"common/xForm",
		"common/xFragment",
		"common/xIcon",
		"common/xIcon",
		"common/xInfoCard",
		"common/xInfoCardItem",
		"common/xInquire",
		/* ********************************** */
		"common/xMenuTreeItem",
		"common/xOprWithMore",
		"common/xRender",
		"common/xSearchList",
		"common/xTable",
		"common/xTablebar",
		"common/xTableColSelected",
		"common/xTableColumn",
		"common/xTableFilter",
		"common/xTableDiv",
		"common/xTransfer",
		"common/xGap",
		"common/xDev",
		/* xItem */
		/* xItemXXXXXXXX */
		"common/xItem/xItem",
		"common/xItem/xItemCheck",
		"common/xItem/xItemCheckboxGroup",
		"common/xItem/xItemCidr",
		"common/xItem/xItemDatetime",
		"common/xItem/xItemInput",
		"common/xItem/xItemIpAddress",
		"common/xItem/xItemNameUrl",
		"common/xItem/xItemRadioGroup",
		"common/xItem/xItemSelect",
		"common/xItem/xItemCascader",
		"common/xItem/xItemSlider",
		"common/xItem/xItemSwitch",
		"common/xItem/xItemMonaco",
		/* ******************* */
		"components/form/xToggleEditor/xToggleText/xToggleText"
	];
}
</script>
