<script>
export default async function () {
	return [
		/* *************** */
		"components/base/xBtn/xBtn",
		"components/base/xBtn/xBtnArray",
		"components/base/xBtn/xBtnGroup",
		/*  */
		"components/navigation/xTabs/xTabs",
		"components/navigation/xTabs/xTabPane",
		"components/data/xTag/xTag",
		"components/data/xTableVir/xTableVir",
		"components/form/xInput/xInput",
		"components/form/xSelect/xSelect",
		"components/form/xInputNumber/xInputNumber",
		"components/form/xCheckbox/xCheckbox",
		"components/other/xCard/xCard",
		"components/other/xBlock/xBlock",
		/*  */
		"components/form/xSelect/xSelect",
		"components/form/xSelect/xOption",
		"components/form/xSelect/xOptionGroup",
		"components/form/xSelect/xSelectDropdown",
		/*  */
		"components/navigation/xDropdown/xDropdown",
		"components/navigation/xDropdown/xDropdownItem",
		"components/navigation/xDropdown/xDropdownMenu",
		/*  */
		"components/other/xScrollbar/xScrollbar",
		/* *************** */
		"common/xMd",
		"common/xItemWrapper",
		"common/xAutoResizer",
		"common/xCellBtnGroup",
		"common/xCellDate",
		"common/xCellEllipsis",
		"common/xCellInput",
		"common/xCellOptions",
		"common/xCellRate",
		"common/xCellSelect",
		"common/xCellSelectSearch",
		"common/xCellSelectOrInput",
		"common/xCellText",
		"common/xColActions",
		"common/xDialog",
		"common/xForm",
		"common/xFragment",
		"common/xIcon",
		"common/xInfoCard",
		"common/xInfoCardItem",
		"common/xInquire",
		"common/xItem",
		"common/xItemCheckboxGroup",
		"common/xItemDatetime",
		"common/xItemInput",
		"common/xItemIpPart",
		"common/xItemNameUrl",
		"common/xItemRadioGroup",
		"common/xItemSelect",
		"common/xItemSwitch",
		"common/xMenuTreeItem",
		"common/xOprWithMore",
		"common/xPageContent",
		"common/xPageTitle",
		"common/xPagination",
		"common/xRender",
		"common/xSearchList",
		"common/xTable",
		"common/xTablebar",
		"common/xTableColSelected",
		"common/xTableColumn",
		"common/xTableFilter",
		"common/xTableDiv",
		"common/xTransfer",
		"common/xGap",
		"common/xDev"
	];
}
</script>
